"""Markdown generator: templates to produce doc-ready output from events."""

import json

def generate_markdown(session_id, session_dir, metadata, ai_summary=None):
    """Generate markdown documentation from captured session.
    
    Args:
        session_id: The session identifier
        session_dir: Path to the session directory
        metadata: Session metadata dict
        ai_summary: Optional AI-generated summary text to include
    """
    
    jsonl_file = session_dir / "events.jsonl"
    markdown_file = session_dir / "summary.md"
    
    # Parse events
    events = []
    try:
        with open(jsonl_file, 'r') as f:
            for line in f:
                if line.strip():
                    events.append(json.loads(line))
    except FileNotFoundError:
        events = []
    
    # Build markdown
    md_lines = []
    md_lines.append(f"# Troubleshooting Session: {metadata.get('name', session_id)}")
    md_lines.append("")
    
    # Metadata
    started_at = metadata.get('started_at', '')
    md_lines.append(f"**Date**: {started_at[:10]}")
    md_lines.append(f"**Session ID**: {session_id}")
    md_lines.append("")
    
    # AI-generated summary
    if ai_summary:
        md_lines.append(ai_summary)
        md_lines.append("")
    
    # Footer
    md_lines.append("---")
    md_lines.append("")
    md_lines.append("*Generated by FixTrace*")
    md_lines.append("")
    
    # Write markdown
    with open(markdown_file, 'w') as f:
        f.write('\n'.join(md_lines))
    
    return markdown_file
