"""Markdown generator: templates to produce doc-ready output from events."""

from pathlib import Path
from datetime import datetime
import json


def generate_markdown(session_id, session_dir, metadata):
    """Generate markdown documentation from captured session."""
    
    jsonl_file = session_dir / "events.jsonl"
    markdown_file = session_dir / "summary.md"
    
    # Parse events
    events = []
    try:
        with open(jsonl_file, 'r') as f:
            for line in f:
                if line.strip():
                    events.append(json.loads(line))
    except FileNotFoundError:
        events = []
    
    # Build markdown
    md_lines = []
    md_lines.append(f"# Troubleshooting Session: {metadata.get('name', session_id)}")
    md_lines.append("")
    
    # Metadata
    started_at = metadata.get('started_at', '')
    md_lines.append(f"**Date**: {started_at[:10]}")
    md_lines.append(f"**Session ID**: {session_id}")
    md_lines.append("")
    
    # Commands and outputs
    md_lines.append("## Steps Taken")
    md_lines.append("")
    
    step_num = 0
    for i, event in enumerate(events):
        if event.get('type') == 'command':
            step_num += 1
            command = event.get('command', '')
            md_lines.append(f"### Step {step_num}")
            md_lines.append("")
            md_lines.append("```bash")
            md_lines.append(command)
            md_lines.append("```")
            md_lines.append("")
            
            # Look for output after this command
            if i + 1 < len(events) and events[i + 1].get('type') == 'output':
                output = events[i + 1].get('content', '')
                if output:
                    md_lines.append("**Output:**")
                    md_lines.append("")
                    md_lines.append("```")
                    md_lines.append(output)
                    md_lines.append("```")
                    md_lines.append("")
    
    # Summary
    md_lines.append("## Summary")
    md_lines.append("")
    md_lines.append("Generated by FixTrace")
    md_lines.append("")
    
    # Write markdown
    with open(markdown_file, 'w') as f:
        f.write('\n'.join(md_lines))
    
    return markdown_file
